In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [23]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Number of data points (rows of X)
N = X.shape[0]

# Create the vector of ones (N x 1)
ones = np.ones((N, 1))

# Identity matrix (N x N)
I = np.eye(N)

# Projection matrix gamma = I - (1/N) * ones * ones^T
gamma = I - (1 / N) * np.dot(ones, ones.T)
print(I)
print((1 / N) * np.dot(ones, ones.T))

# Apply the projection to the data matrix X
Z = np.dot(gamma, X)

# Check the rank of the original matrix X and the projected matrix Z
rank_X = np.linalg.matrix_rank(X)
rank_Z = np.linalg.matrix_rank(Z)

print("Original matrix X:")
print(X)
print("\nProjection matrix γ:")
print(gamma)
print("\nTransformed matrix Z = γX:")
print(Z)
print(f"\nRank of original matrix X: {rank_X}")
print(f"Rank of transformed matrix Z: {rank_Z}")

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
Original matrix X:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Projection matrix γ:
[[ 0.66666667 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667]]

Transformed matrix Z = γX:
[[-3.00000000e+00 -3.00000000e+00 -3.00000000e+00]
 [ 2.77555756e-16  4.44089210e-16  6.10622664e-16]
 [ 3.00000000e+00  3.00000000e+00  3.00000000e+00]]

Rank of original matrix X: 2
Rank of transformed matrix Z: 1
